# Generated by Django 5.2.5 on 2025-08-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=290.0, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(default='yookassa', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
