# Generated by Django 5.2.5 on 2025-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_subscription_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение')], default='text', max_length=10, verbose_name='Источник'),
        ),
    ]
