# Generated by Django 5.2.5 on 2025-08-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_subscription_amount_subscription_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа'),
        ),
    ]
